import RepoCard from "./RepoCard";

type Repo = {
  id: number;
  name: string;
  stars: string;
  desc: string;
  reason: string;
};

type Props = {
  repoCards: Repo[];
};

export default function RecommendationPanel({ repoCards }: Props) {
  return (
    <div className="rounded-3xl border border-slate-200 bg-slate-50 p-4 md:p-5">
      <div className="mb-4 flex items-center justify-between">
        <div>
          <p className="text-sm font-semibold text-slate-900">推荐结果</p>
          <p className="text-sm text-slate-500">Top 2 repositories</p>
        </div>
        <span className="rounded-full bg-white px-3 py-1 text-xs text-slate-500 ring-1 ring-slate-200">
          Generated by LLM
        </span>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        {repoCards.map((repo) => (
          <RepoCard key={repo.id} repo={repo} />
        ))}
      </div>
    </div>
  );
}
